services:
  technitium:
    image: technitium/dns-server:latest
    container_name: technitium
    hostname: technitium
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "5380:5380/tcp"
    volumes:
      - technitium-data:/etc/dns
    environment:
      - DNS_SERVER_DOMAIN=technitium.uptonx.local
      - DNS_SERVER_ADMIN_PASSWORD=admin

volumes:
  technitium-data:
