http:
  routers:
    nomad:
      rule: "Host(`nomad.uptonx.com`)"
      service: nomad
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    technitium:
      rule: "Host(`dns.uptonx.com`)"
      service: technitium
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    traefik-dashboard:
      rule: "Host(`traefik.uptonx.com`)"
      service: traefik-dashboard
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

  services:
    nomad:
      loadBalancer:
        servers:
          - url: "http://192.168.1.101:4646"

    technitium:
      loadBalancer:
        servers:
          - url: "http://192.168.1.51:5380"

    traefik-dashboard:
      loadBalancer:
        servers:
          - url: "http://192.168.1.15:8080"
