http:
  routers:
    technitium:
      rule: "Host(`dns.uptonx.com`)"
      service: technitium
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    traefik-dashboard:
      rule: "Host(`traefik.uptonx.com`)"
      service: traefik-dashboard
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    email-rag:
      rule: "Host(`email-rag.uptonx.com`)"
      service: email-rag
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    chat:
      rule: "Host(`chat.uptonx.com`)"
      service: chat
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    audio:
      rule: "Host(`audio.uptonx.com`)"
      service: audio
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

  services:
    technitium:
      loadBalancer:
        servers:
          - url: "http://192.168.1.51:5380"

    traefik-dashboard:
      loadBalancer:
        servers:
          - url: "http://192.168.1.15:8080"

    email-rag:
      loadBalancer:
        servers:
          - url: "http://192.168.1.110:3000"

    chat:
      loadBalancer:
        servers:
          - url: "http://192.168.1.110:8080"

    audio:
      loadBalancer:
        servers:
          - url: "http://192.168.1.74:8090"
