version: "3.8"

services:
  grafana:
    image: grafana/grafana-oss:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/home.json
    volumes:
      - data:/var/lib/grafana
    networks:
      - proxy
      - internal
    ports:
      - "3002:3000"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  prometheus:
    image: prom/prometheus:latest
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    volumes:
      - prom_data:/prometheus
    networks:
      - proxy
      - internal
    ports:
      - "9090:9090"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  loki:
    image: grafana/loki:3.4
    command: -config.file=/etc/loki/loki.yml
    configs:
      - source: loki_config
        target: /etc/loki/loki.yml
    volumes:
      - loki_data:/loki
    networks:
      - internal
    ports:
      - "3100:3100"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  promtail:
    image: grafana/promtail:3.4
    command: -config.file=/etc/promtail/promtail.yml
    configs:
      - source: promtail_config
        target: /etc/promtail/promtail.yml
    volumes:
      - /var/log:/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
    deploy:
      mode: global

configs:
  prometheus_config:
    file: ./prometheus.yml
  loki_config:
    file: ./loki.yml
  promtail_config:
    file: ./promtail.yml

volumes:
  data:
  prom_data:
  loki_data:

networks:
  proxy:
    external: true
  internal:
    external: true
