"""HTML report generation for Image Detail Lab cases."""

import base64
import os
from datetime import datetime
from io import BytesIO

from PIL import Image


def export_html_report(
    case_dir: str,
    original: Image.Image,
    variants: dict[str, Image.Image],
    analyses: dict[str, dict],
    rankings: list[tuple[str, float, str]],
    suggestions: list[str],
    notes: str,
    selected: set[str],
) -> str:
    """Generate an HTML report with embedded images. Returns path to report."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    case_name = os.path.basename(case_dir)
    orig_b64 = _img_to_b64(original, 600)

    variant_cards = ""
    for rank, (name, score, reason) in enumerate(rankings, 1):
        img_b64 = _img_to_b64(variants[name], 400)
        a = analyses.get(name, {})
        star = " &#9733; SELECTED" if name in selected else ""
        variant_cards += f"""
        <div class="variant">
            <h3>#{rank}: {name}{star}</h3>
            <img src="data:image/png;base64,{img_b64}" />
            <table>
                <tr><td>Score</td><td>{score}</td></tr>
                <tr><td>Sharpness</td><td>{a.get("sharpness", "-")}</td></tr>
                <tr><td>Contrast</td><td>{a.get("contrast", "-")}</td></tr>
                <tr><td>Detail</td><td>{a.get("detail", "-")}</td></tr>
                <tr><td>Noise</td><td>{a.get("noise", "-")}</td></tr>
                <tr><td>Brightness</td><td>{a.get("brightness", "-")}</td></tr>
            </table>
            <p class="reason">{reason}</p>
        </div>"""

    suggestions_li = "\n".join(f"<li>{s}</li>" for s in suggestions)
    notes_html = notes.replace("\n", "<br>") if notes else "<em>No notes.</em>"

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Image Detail Lab &mdash; {case_name}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         margin: 2em; background: #f5f5f5; color: #333; }}
  h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: .3em; }}
  h2 {{ color: #2c3e50; margin-top: 1.5em; }}
  .meta {{ color: #666; font-size: .9em; }}
  .original {{ text-align: center; margin: 1em 0; }}
  .original img {{ max-width: 600px; border: 1px solid #ddd; }}
  .variants {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(420px, 1fr)); gap: 1.5em; }}
  .variant {{ background: #fff; padding: 1em; border-radius: 8px;
              box-shadow: 0 1px 3px rgba(0,0,0,.1); }}
  .variant img {{ max-width: 100%; border: 1px solid #eee; }}
  .variant table {{ width: 100%; margin: .5em 0; font-size: .9em; }}
  .variant td {{ padding: 2px 8px; border-bottom: 1px solid #eee; }}
  .variant td:first-child {{ font-weight: bold; width: 100px; }}
  .reason {{ font-style: italic; color: #555; font-size: .9em; }}
  .suggestions {{ background: #eaf6ff; padding: 1em; border-radius: 8px; }}
  .suggestions li {{ margin: .3em 0; }}
  .notes {{ background: #fff; padding: 1em; border-radius: 8px; white-space: pre-wrap; }}
  .disclaimer {{ font-size: .8em; color: #999; margin-top: 2em;
                 border-top: 1px solid #ddd; padding-top: 1em; }}
</style>
</head>
<body>
<h1>Image Detail Lab Report</h1>
<p class="meta">Case: {case_name} &mdash; Generated: {timestamp}</p>

<h2>Original Image</h2>
<div class="original"><img src="data:image/png;base64,{orig_b64}" /></div>

<h2>AI Guidance</h2>
<div class="suggestions"><ul>{suggestions_li}</ul></div>

<h2>Enhancement Variants (Ranked)</h2>
<div class="variants">{variant_cards}</div>

<h2>Notes</h2>
<div class="notes">{notes_html}</div>

<p class="disclaimer">
  Generated by Image Detail Lab. Scores are heuristic estimates based on measurable
  image properties. They do not constitute definitive forensic findings. Visual
  inspection should always guide final interpretation.
</p>
</body>
</html>"""

    report_path = os.path.join(case_dir, "report.html")
    with open(report_path, "w") as f:
        f.write(html)
    return report_path


def _img_to_b64(img: Image.Image, max_size: int = 600) -> str:
    """Resize and base64-encode an image for HTML embedding."""
    thumb = img.copy()
    thumb.thumbnail((max_size, max_size), Image.LANCZOS)
    if thumb.mode not in ("RGB", "L"):
        thumb = thumb.convert("RGB")
    buf = BytesIO()
    thumb.save(buf, format="PNG")
    return base64.b64encode(buf.getvalue()).decode()
