version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - target: 9000
        published: 9000
        mode: host
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/nas/stacks/portainer:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(`192.168.1.80`) && PathPrefix(`/portainer`)"
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  proxy:
    external: true
