version: "3.8"

services:
  app:
    image: louislam/uptime-kuma:1
    volumes:
      - data:/app/data
    networks:
      - proxy
    ports:
      - "3001:3001"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  data:

networks:
  proxy:
    external: true
